name: Basic CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 10 * * *'  # каждый день в 10:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Prepare .env file
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_BASE64 }}
        run: |
          echo "$ENV_FILE_CONTENT" | base64 -d > .env

      - name: Run tests
        run: npm run test-mocha

      - name: Publish JUnit test results
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'reports/**/*.xml'

      - name: Show test summary
        run: echo "Tests completed. Review output above."

      - name: Upload error screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots
          path: ./errorShots/
