name: Basic CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 10 * * *'  # каждый день в 10:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Prepare .env file
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_BASE64 }}
        run: |
          echo "$ENV_FILE_CONTENT" | base64 -d > .env

      - name: Run tests
        run: npm run test-wdio CI

      - name: Publish JUnit test results
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'reports/**/*.xml'

      - name: Show test summary
        run: echo "Tests completed. Review report above."
